package com.netcracker.ivanlavrov.myTestTask.service;

import com.netcracker.ivanlavrov.myTestTask.domain.Customer;
import com.netcracker.ivanlavrov.myTestTask.web.dto.CustomerDTO;

public interface CustomerApi {

    /**
     * This method adds a customer to DB.
     * CustomerDTO is input from API consumer.
     * In case customer with the same name exists, API will return an error.
     *
     * @param customer {@link com.netcracker.ivanlavrov.myTestTask.web.dto.CustomerDTO}
     */
    void addCustomer(final CustomerDTO customer);

    /**
     * This method updates customer in DB. You have to specify some parameters, some can be null.
     * In case customer with such customerId does not exists, API will return an error.
     * @param id - customer ID generated by MongoDB.
     * @param name - customer's legal name.
     * @param description - short description about customer.
     * @param email - customer's email address. No validation.
     * @param address - customer's postal address.
     * @return
     */
    Customer updateCustomer(String id, String name, String description, String email, String address);

    /**
     * This method returns customer by the given customerId.
     * @param id - customer ID.
     * @return Customer object.
     */
    Customer getCustomerById(String id);

    /**
     * This methiod removes a customer from DB. All customer's employees will be removed as well.
     * @param id - customer ID.
     */
    void deleteCustomer(String id);
}
